server:
  port: 8888

spring:
  application:
    name: spring-config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:123VladimiR123/server-config.git
          username: username
          password: password
          default-label: main
          search-paths: "{application}"